env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo

    # For rclone with google drive or any cloud! After first commit pushing, login to https://cirrus-ci.com , click top left corner 3 dot menu, click repository(yourname/aosp-builder) > Repository Settings > Secured Variables > enter content of ~/.config/rclone/rclone.conf (from pc where you setup rclone) > ENCRYPT, copy that ENCRYPTED hash
    # ENCRYPTED variables is unique for every repository, so you cant use my one, create you rclone config https://rclone.org/drive/#making-your-own-client-id
    rclone_config: "ENCRYPTED[095e5f22a11a3f89599ffa8a7a606fd5392e96dc2fed3e4188cab37b8908fa5783ff49c2fa0b71f2590907779e83347e]"
    mybot: "ENCRYPTED[15249f6e81401d3eed6569930d367b12560bebd0e3eaa042df08582439ee676695ec7dc6f922f83dbec2ea729c5c31bf]"
    chatid: "ENCRYPTED[1dddf17bc8bad82d21529b9803efbf8a4e4b979f937d1073bc64da0e18700247691f883d4d74615ee50c1002e6691cfe]"
    apicode: "ENCRYPTED[347ee83b611cce14da467d24dad070df148a7be9ce841bf9efcbf284dd5dda8ecbbeaa52069747abdd95210298d03840]"

task:
    name: aosp # Project name
    timeout_in: 120m # Otherwise it will timeout at 60m automatically, 120m highest in free account
    container:
      image: apon77/aosp:latest # It has built in setup environment + repo, aria2, rclone, pigz, username ci, and email ci@ci.ci [You can use your own docker image if you want, or you can use this one too!]
      cpu: 8  #8 cpu for dummy build, 10 or more cpu for final build, sometimes more than 8 cpu will cause a timelock, so you wont be able to run ci again within few hours, in build script use -j8 or -j10 depending what you used here, otherwise low memory issue will happen, 16cpu highest
      memory: 24G # So that we can have ram when needed, 24G highest
    download_ccache_background_script: # To download ccache in background
      - ./download_ccache # Ccache download script
    sync_script: # To sync source
      - ./sync # Source sync script
    monitor_background_script: # To monitor ccache and machine status every minute, runs in background
      - ./monitor # Monitor script
    build_script: # Actual build script foreground
      - ./build # Build script to run
    upload_ccache_script: # Upload ccache to cloud foreground
      - ./upload_ccache # Ccache uploading script
