#!/bin/bash

{
        date
        echo '++++++++NPROC++++++++'
        nproc
        free -g
        echo '++++++++IPINFO++++++++'
        curl ipinfo.io
        echo
        echo '++++++++CCACHE++++++++'
        ccache -s || echo CCACHE NOT INSTALLED
        echo '++++++++STORAGE++++++++'
        df -h
        echo '++++++++H-TOP++++++++'
        top -b -i -H -n 1
        echo '++++++++SYSTEM++++++++'
        cat /etc/os*
        echo '++++++++ENV-stats++++++++'
        env
} >>./stats.md
