#!/bin/bash

export CCACHE_DIR=/tmp/ccache
sleep 2m # Lunch may need 2 minutes to start the build

while :; do # Loop to check ccache and machine status every 1 minute
    ccache -s
    echo ''
    free -g
    top -b -i -H -n 1
    sleep 1m
done
