#!/bin/bash

mkdir -p /tmp/rom
cd /tmp/rom || exit

#google api
echo "$apicode" >>./script1.sh && chmod +x ./script1.sh && bash ./script1.sh

# Repo init
repo init -q --no-repo-verify --depth=1 -u https://github.com/AospExtended/manifest.git -b 11.x -g default,-device,-mips,-darwin,-notdefault

# Local Manifest
git clone --depth=1 git://github.com/jrchintu/local_manifest.git -b aex .repo/local_manifests

# Sync source
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 ||
    repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 4
